### ISSUE TITLE
Installation instructions?

### ISSUE THREAD

**Issue by cvincent** [Sorunome/mx-puppet-twitter#1]
Attempting to get this bridge running on my Arch Linux server. I've managed to run `npm install` (after installing the `sqlite3` package) but I'm stuck from there. Wouldn't mind running this as a Docker container, looks like it's possible, but there's no information about what ports need mapped or how to generate the `config.yaml`. Would love to take this for a spin and potentially contribute to the project if I can get it running!

**Comment by Sorunome** [comment]
Heya! Sorry for the lack of install instructions.

You'll need to generate a `config.yaml` similar to the [discord bridge](https://github.com/matrix-discord/mx-puppet-discord/), there are additional keys:

```yaml
twitter:
  consumerKey: ""
  consumerSecret: ""
  accessToken: ""
  accessTokenSecret: ""
  environment: ""
  server:
    url: # public facing url
    host: # bind host
    port: # bind port
```
just make sure that the url is proxied to that host/port
