### ISSUE TITLE
failed to register new webhook

### ISSUE THREAD

**Issue by ericmigi** [Sorunome/mx-puppet-twitter#11]
Any suggestions on how I can debug this one?

```
Apr-6 05:41:01.653 [PuppetBridge] info: Application service started!                                                                                          
Apr-6 05:41:01.653 [PuppetBridge] info: Setting bridge user data...                                                                                           
Apr-6 05:41:04.435 [TwitterPuppet:Twitter] error: Failed to register new webhook Error: Non-200 response code during CRC GET request (i.e. 404, 500, etc).    
    at Request._callback (/opt/mx-puppet-twitter/node_modules/twitter-webhooks/lib/helpers.js:27:33)                                                          
    at Request.self.callback (/opt/mx-puppet-twitter/node_modules/request/request.js:185:22)                                                                  
    at Request.emit (events.js:316:20)                                                                                                                        
    at Request.<anonymous> (/opt/mx-puppet-twitter/node_modules/request/request.js:1161:10)                                                                   
    at Request.emit (events.js:316:20)
    at IncomingMessage.<anonymous> (/opt/mx-puppet-twitter/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:422:28)
    at IncomingMessage.emit (events.js:328:22)
    at endReadableNT (_stream_readable.js:1201:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 214,
  statusCode: 400,
  body: { errors: [ [Object] ] }
}
Apr-6 05:41:04.436 [PuppetBridge] info: Activating users...
```

config.yaml
```
bridge:
  port: 29322
  domain: nova.chat
  bindAddress: 0.0.0.0
  homeserverUrl: https://asmux.nova.chat
  loginSharedSecretMap:
    nova.chat: 

homeserverUrlMap:
  nova.chat: https://asmux.nova.chat

namePatterns:
  user: :name [:team? - :team,]  Twitter
  room: :name [:team? - :team,]  Twitter
  group: :name - Twitter

logging:
  console: info
  files:
  - file: /data/debug.log
    level: silly
    disable:
    - 'PresenceHandler'
    - 'bot-sdk-Metrics'
presence:
  enabled: false
database:
  filename: /data/twitter.db
provisioning:
  whitelist:
    - "@testtwo:nova\\.chat"
  sharedSecret: 
  apiPrefix: /_matrix/provision
twitter:
  consumerKey: ""
  consumerSecret: ""
  accessToken: "-"
  accessTokenSecret: ""
  environment: "novadev"
  server:
    url: https://testtwo.novabridge.dev/twitter
    host: 0.0.0.0
    port: 4567
```

**Comment by Sorunome** [comment]
Heya, the config changed that there is only one webserver listening now. You will have to redirect your http traffic to port 29322 (where your bridge is listening) instead of the one defined in `twitter.server`. You still have to set with `twitter.server.url` where twitter can reach your bridge, and you can now also set in `twitter.server.path` what the path of the webhook should be (defaults to `/webhook`)

Soru should really update the sample config...

**Comment by Sorunome** [comment]
This is, for example, the config soru uses:

```
bridge:
  port: 8436
  domain: sorunome.de
  homeserverUrl: https://sorunome.de
twitter:
  server:
    url: https://sorunome.de
    path: /_matrix/twitter/webhook
```

That means she has to redirect `https://sorunome.de/_matrix/twitter/webhook` to `localhost:8436`
